USE BEEL_BALAM;
--CONSULTAS SIMPLES
--1. VER TRAMO (I)
	SELECT *FROM TRAMO WHERE NOMBRE_TR = 'TC2';

--2. VER INFORMACIÓN DE LA TARJETA (T)
	SELECT *FROM TARJETA WHERE NUM_TARJETA = '1134567890123456'

--3. VER INFORMACIÓN DE LA CTA DE USUARIO (A)
	DECLARE @nUsuario VARCHAR(25);
	SELECT @nUsuario = 'bellita';
	SELECT NOMBRE_U,CORREO_U,NUM_CEL_U,PTOS_ACUM_U,NUM_TARJETA_U FROM USUARIO WHERE NOMBRE_U=@nUsuario;

--4. VER INFORMACIÓN DE LA RESERVA (I)
	SELECT *FROM RESERVA WHERE COD_R = 5;

--5. VER INFORMACIÓN DEL CLIENTE (T)
	SELECT *FROM CLIENTE WHERE ID_CLIENTE  = 5;

--CONSULTAS MULTITABLA
--1. VER QUÉ TARJETA TIENE CIERTO USUARIO (A)
	DECLARE @nUsuarioT VARCHAR(25);
	SELECT @nUsuarioT = 'bellita';
	SELECT NOMBRE_U,NUM_TARJETA FROM USUARIO,TARJETA WHERE NUM_TARJETA=NUM_TARJETA_U 
	AND NOMBRE_U=@nUsuarioT;
	
--2. VER NOMBRE DE USUARIO Y CLIENTE(S) RELACIONADO(S) (I)
	SELECT RESERVA.ID_CLIENTE ,NOMBRE_U FROM RESERVA,CLIENTE 
	WHERE RESERVA.ID_CLIENTE = '500' GROUP BY RESERVA.ID_CLIENTE,RESERVA.NOMBRE_U

--3. VER LAS ESTACIONES DE CIERTO TRAMO (T)
	SELECT  TRAMO.NOMBRE_TR,ESTACIONES.NOMBRE_EST FROM TRAMO,ESTACIONES WHERE ESTACIONES.NOMBRE_TR = TRAMO.NOMBRE_TR 
	GROUP BY TRAMO.NOMBRE_TR,ESTACIONES.NOMBRE_EST

	SELECT  ESTACIONES.NOMBRE_EST,ESTACIONES.NOMBRE_TR FROM TRAMO,ESTACIONES WHERE ESTACIONES.NOMBRE_TR = 'TS2' 
	GROUP BY ESTACIONES.NOMBRE_EST,ESTACIONES.NOMBRE_TR

--4. VER LA RESERVA DE CIERTO CLIENTE (A)
	DECLARE @idCliente INT;
	SELECT @idCliente = 502;
	SELECT CLIENTE.ID_CLIENTE,PRIMER_NOMBRE_C,SEGUNDO_NOMBRE_C,
	PRIMER_APELLIDO_C,SEGUNDO_APELLIDO_C, COD_R,FECHA_R,NOMBRE_TR FROM CLIENTE,RESERVA
	WHERE CLIENTE.ID_CLIENTE=RESERVA.ID_CLIENTE AND CLIENTE.ID_CLIENTE=@idCliente;
	
--5. VER QUÉ RESERVA CIERTO USUARIO (I)
	SELECT *FROM RESERVA WHERE NOMBRE_U = 'richie'

--CONSULTAS DE RESUMEN
--1. ¿CUÁNTAS RESERVAS SON DE CIERTA FECHA EN CIERTO TRAMO? (T)
	SELECT COUNT(*) AS NUM_RESERVAS FROM RESERVA WHERE RESERVA.FECHA_R = '12/10/2021' AND RESERVA.NOMBRE_TR = 'TC2'

--2. ¿CUÁNTOS CLIENTES HAY DE CIERTO PAÍS? (A)
	DECLARE @nacionalidad VARCHAR(25);
	SELECT @nacionalidad = 'MEXICANA';
	SELECT COUNT(ID_CLIENTE) AS NUM_PAIS FROM CLIENTE WHERE NACIONALIDAD_C=@nacionalidad;

--3. ¿CUÁNTOS CLIENTES HAY DE CIERTA EDAD? (I)
	SELECT COUNT(*) FROM CLIENTE WHERE EDAD_C =12 GROUP BY EDAD_C

--4. ¿CUÁL ES EL PROMEDIO DEL COSTO DE UN BOLETO? (T)
	SELECT AVG(COSTO_TR) AS PROMEDIO_COSTO_BOLETO FROM TRAMO

--5. ¿EN QUE TRAMO VIAJAN MÁS PERSONAS?
	SELECT COUNT(NOMBRE_TR),NOMBRE_TR FROM RESERVA GROUP BY NOMBRE_TR HAVING COUNT(NOMBRE_TR) = (SELECT MAX(N.CONTADOR) FROM
	(SELECT COUNT(NOMBRE_TR) AS CONTADOR FROM RESERVA GROUP BY NOMBRE_TR) AS N)