USE BEEL_BALAM;

--SUBCONSULTA PARA CONOCER EL NUMERO DE CLIENTES MAYORES DE EDAD
SELECT  COUNT(*) AS NUM_CLIENTES_MAYORES_DE_EDAD FROM RESERVA 
WHERE ID_CLIENTE IN (SELECT ID_CLIENTE FROM CLIENTE WHERE EDAD_C >18 GROUP BY ID_CLIENTE)

--SUBCONSULTA PARA CONOCER EL #DE CLIENTES EXTRANJEROS REGISTRADOS CON CIERTO USUARIO
DECLARE @usuario VARCHAR(25);
SET @usuario = 'richi'
SELECT COUNT(*) AS NUM_EXTRANJEROS FROM CLIENTE 
WHERE ID_CLIENTE IN(SELECT ID_CLIENTE FROM RESERVA WHERE NOMBRE_U = @usuario GROUP BY ID_CLIENTE) AND NACIONALIDAD_C <> 'MEXICANA'

