USE BEEL_BALAM;

--SUBCONSULTA PARA CONOCER EL NUMERO DE CLIENTES MAYORES DE EDAD
SELECT  COUNT(*) AS NUM_CLIENTES_MAYORES_DE_EDAD FROM RESERVA 
WHERE ID_CLIENTE IN (SELECT ID_CLIENTE FROM CLIENTE WHERE EDAD_C >18 GROUP BY ID_CLIENTE)

--SUBCONSULTA PARA CONOCER EL #DE CLIENTES EXTRANJEROS REGISTRADOS CON CIERTO USUARIO
DECLARE @usuario VARCHAR(25);
SET @usuario = 'richi'
SELECT COUNT(*) AS NUM_EXTRANJEROS FROM CLIENTE 
WHERE ID_CLIENTE IN(SELECT ID_CLIENTE FROM RESERVA WHERE NOMBRE_U = @usuario GROUP BY ID_CLIENTE) AND NACIONALIDAD_C <> 'MEXICANA'


--PENDIENTE DE TERMINAAAAR 
--SUBCONSULTA PARA VER QUÉ CLIENTE ES EL QUE LE HA GENERADO UNA MAYOR CANTIDAD 
--DE PUNTOS A CIERTO USUARIO 
DECLARE @nUsuario VARCHAR(25);
SET @nUsuario = 'sergio123';
SELECT PRIMER_NOMBRE_C,SEGUNDO_NOMBRE_C,PRIMER_APELLIDO_C,SEGUNDO_APELLIDO_C FROM CLIENTE 
WHERE ID_CLIENTE = ALL(); --SELECT COSTO_R FROM RESERVA


SELECT * FROM CLIENTE
SELECT * FROM RESERVA
SELECT * FROM USUARIO
insert into RESERVA values (1,'12/12/2021','sergio123','TC1',501,2,200)
insert into CLIENTE values (505,'NAYE','A','S','C',17,'MEXICANA')
insert into CLIENTE values (507,'ALI','A','S','C',24,'MEXICANA')
DELETE FROM USUARIO WHERE NOMBRE_U='NOOOO'
