USE BEEL_BALAM

--Creando la vista para ver a los usuarios
CREATE VIEW DATA_USUARIO AS  (SELECT NOMBRE_U,CORREO_U,NUM_CEL_U,PTOS_ACUM_U,NUM_TARJETA_U FROM USUARIO )

--Creando la vista para obtener los nombres de usuario
CREATE VIEW GET_USERNAMES AS (SELECT NOMBRE_U FROM USUARIO)

--Creando la vista para ver la relación entre clientes y usuarios
CREATE VIEW CLIENTE_USUARIO AS 
	SELECT RESERVA.NOMBRE_U,CLIENTE.PRIMER_NOMBRE_C,CLIENTE.SEGUNDO_NOMBRE_C,CLIENTE.PRIMER_APELLIDO_C,CLIENTE.SEGUNDO_APELLIDO_C,CLIENTE.EDAD_C,CLIENTE.NACIONALIDAD_C
	FROM RESERVA INNER JOIN CLIENTE ON RESERVA.ID_CLIENTE = CLIENTE.ID_CLIENTE
