USE BEEL_BALAM

--Creando la vista para ver a los usuarios
CREATE VIEW DATA_USUARIO AS  (SELECT NOMBRE_U,CORREO_U,NUM_CEL_U,PTOS_ACUM_U,NUM_TARJETA_U FROM USUARIO )

--Creando la vista para obtener los nombres de usuario
CREATE VIEW GET_USERNAMES AS (SELECT NOMBRE_U FROM USUARIO)

--Creando la vista para ver la relación entre clientes y usuarios
CREATE VIEW CLIENTE_USUARIO AS 
	SELECT RESERVA.NOMBRE_U,CLIENTE.PRIMER_NOMBRE_C,CLIENTE.SEGUNDO_NOMBRE_C,CLIENTE.PRIMER_APELLIDO_C,CLIENTE.SEGUNDO_APELLIDO_C,CLIENTE.EDAD_C,CLIENTE.NACIONALIDAD_C
	FROM RESERVA INNER JOIN CLIENTE ON RESERVA.ID_CLIENTE = CLIENTE.ID_CLIENTE

--Creando la vista para ver la información de las reservas 
DROP VIEW RESERVA_USUARIO
CREATE VIEW RESERVA_USUARIO AS 
	SELECT NOMBRE_U,COD_R,PRIMER_NOMBRE_C,SEGUNDO_NOMBRE_C,
	PRIMER_APELLIDO_C,SEGUNDO_APELLIDO_C,FECHA_R,
	RESERVA.NOMBRE_TR,EST_I,EST_F,COSTO_R
	FROM RESERVA,CLIENTE,TRAMO 
	WHERE RESERVA.ID_CLIENTE=CLIENTE.ID_CLIENTE AND 
	RESERVA.NOMBRE_TR=TRAMO.NOMBRE_TR;

SELECT * FROM RESERVA_USUARIO
SELECT * FROM CLIENTE
SELECT * FROM RESERVA
SELECT NOMBRE_U FROM RESERVA_CLIENTE

--Creando la vista para ver las reservas del cliente
CREATE VIEW RESERVA_CLIENTE AS
	SELECT COD_R,FECHA_R,NOMBRE_TR,PRIMER_NOMBRE_C,SEGUNDO_NOMBRE_C,
	PRIMER_APELLIDO_C,SEGUNDO_APELLIDO_C,EDAD_C,NACIONALIDAD_C,COSTO_R
	FROM RESERVA,CLIENTE WHERE RESERVA.ID_CLIENTE=CLIENTE.ID_CLIENTE;

SELECT COD_R FROM RESERVA_CLIENTE